### ISSUE TITLE
Add static linking support

### ISSUE THREAD

**Issue by timpokorny** [timpokorny/cpptask#2]
#### Summary
----
`<cpptask>` only supports generating dynamic libraries and executables.

#### What I'm trying to do
----
Produce a library (file.a) that users can statically link with their apps.

#### Minimum Steps to Reproduce
----
Entering "static" in the `outtype` attribute of the `<cpptask>` declaration causes an error stating that it is not a valid option
 
#### Expected and Observed Results
----
 * Should be able to enter `static` as an `outtype` option
 * Static library (`file.a`) will be produced in the output directory on completion

#### Work Breakdown
----
`<tbc>`

**Comment by michaelrfraser** [comment]
Implemented (hopefully) in https://github.com/timpokorny/cpptask/pull/5

I've tested this under msvc, but not gcc.

**Comment by timpokorny** [comment]
Closing. Will have tests for Mac OSX soon enough and will re-open from there if required.
