### ISSUE TITLE
Include support for VC12 (Visual Studio 2013)

### ISSUE THREAD

**Issue by michaelrfraser** [timpokorny/cpptask#7]
### Summary
---
As a C++ developer I require the ability to link to the VC12 runtime, so that I can build libraries for projects that are themselves built against VC12

### What I'm trying to do
---
I'm developing a plugin DLL for an architecture that is itself compiled against VC12. The plugin needs to be linked against the same runtime as to avoid compatibility warnings/errors.

### Work Breakdown
---

- Add VC12 as a valid compiler type

**Comment by michaelrfraser** [comment]
PR created at https://github.com/timpokorny/cpptask/pull/8

- Added VC12 entries to CompilerType and Version enums

**Comment by timpokorny** [comment]
Merged into `master`
