### ISSUE TITLE
Include support for VC14 (Visual Studio 2015)

### ISSUE THREAD

**Issue by michaelrfraser** [timpokorny/cpptask#9]
### Summary

---

As a C++ developer I require the ability to link to the VC14 runtime, so that I can build libraries for projects that are themselves built against VC14

### What I'm trying to do

---

I'm developing a plugin DLL for an architecture that is itself compiled against VC14. The plugin needs to be linked against the same runtime as to avoid compatibility warnings/errors.

### Work Breakdown

---
- Add VC14 as a valid compiler type

**Comment by timpokorny** [comment]
Merged.
